program: train_sweep.py
method: bayes
metric:
  name: loss
  goal: minimize
parameters:
  latent_dim:
    values: [16, 24, 32, 48, 64]
  learning_rate:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.01
  beta:
    values: [1, 2, 5, 10]
  batch_size:
    value: 64
  epochs:
    value: 10
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}
